### ISSUE TITLE
AddUser执行完报错

### ISSUE THREAD

**Issue by ybdt** [M0nster3/RpcsDemo#2]
AddUser首次执行可以成功添加用户，第二次执行会报错：[!] Samconnect error

或者哪里有SamConnect的API文档，谢谢 :)

**Comment by ybdt** [comment]
是我改代码后，localhost那里改错了，没问题

**Comment by M0nster3** [comment]
可以去微软官方文档里面看一下 你的报错是什么编号




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "M0nster3/RpcsDemo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月11日(星期二) 中午1:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[M0nster3/RpcsDemo] AddUser执行完报错 (Issue #2)





 
AddUser首次执行可以成功添加用户，第二次执行会报错：[!] Samconnect error
 
或者哪里有SamConnect的API文档，谢谢 :)
